name: Android CI

on:
  # Triggers the workflow on push or pull request events but only for default and protected branches
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Change wrapper permissions
        run: chmod +x ./gradlew


     
    
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1
      
      - uses: actions/cache@v2
        with:
          path: |
                 ~/.gradle/caches
                 ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-


   #   - name: Run tests
   #     run: ./gradlew test


    
      - name: Build project
        run: |
             ./gradlew build
        
        
        
        
             APKSIGNER="/usr/local/lib/android/sdk/build-tools/31.0.0/apksigner" 
             echo "Signing  APK...."
             cd /home/runner/work/android-java-terminal/android-java-terminal/
             
             
             
             echo "${{ secrets.SIGNING_KEY_64_JKS }}" | base64 -d > SIGNING_KEY.jks 
             echo "${{ secrets.PASSWORD_64 }}" | base64 -d  > PASSWORD.txt
             echo "make copy-paste this HEX to converter HEX to base64 to get base64 code and paste it
             in  secret action " 
             xxd -p SIGNING_KEY.jks
             
             
             

             $APKSIGNER sign  --ks  SIGNING_KEY.jks   $PROJ/app/build/outputs/apk/release/hello.apk  < PASSWORD.txt
             $APKSIGNER verify -v  -v4-signature-file $PROJ/app/build/outputs/apk/release/hello.apk.idsig $PROJ/app/build/outputs/apk/release/hello.apk 
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
         name: app-debug
         path: app/build/outputs/apk/debug/app-debug.apk  
        
        
        
